description = "Read a file and display its contents"
prompt = """Read the file at the path: {{args}}

IMPORTANT INSTRUCTIONS:
- ONLY use the Read tool to read the specified file
- DO NOT make any edits or changes
- DO NOT create any new files
- DO NOT run any commands
- DO NOT analyze or comment on the contents
- Simply read the file and display its contents
- After reading, stop immediately without any additional explanation or summary"""
