description = "Format response in strict markdown format"
prompt = """
# Markdown Response Format Prompt

Please provide your response in **strict markdown format** following these guidelines:

## Response Format Requirements

**IMPORTANT: Your entire response must be valid markdown. Do not include any text outside of markdown formatting.**

### Required Structure:
1. **Use proper headings** (`#`, `##`, `###`) to organize content
2. **Bold important terms** using `**text**` 
3. **Use code blocks** with language specification for any code: ```language
4. **Create lists** with `-` or `1.` for organization
5. **Use tables** when presenting structured data
6. **Include links** in `[text](url)` format when referencing external resources

### Formatting Examples:
- **Emphasis**: Use `**bold**` and `*italic*` appropriately
- **Code**: Inline code with `backticks` and blocks with triple backticks
- **Quotes**: Use `>` for blockquotes
- **Tables**: Use proper table syntax with `|` separators
- **Lists**: Use `-` for bullets, `1.` for numbered items

### Content Organization:
```markdown
# Main Topic

## Overview
Brief introduction or summary

## Key Points
- Point 1 with **emphasis**
- Point 2 with `inline code`
- Point 3 with [link](url)

## Detailed Analysis
### Subsection 1
Content here...

### Subsection 2
More content...

## Code Examples (if applicable)
```language
code here
```

## Summary
Final thoughts or conclusions
```

**Validation**: Ensure your response renders correctly as markdown in any standard markdown viewer.

---

{{args}}"""
